image:
  name: mcr.microsoft.com/playwright:v1.30.0-focal
options:
  size: 4x

pipelines:
  default:
    - parallel:
        - step:
            name: Shard 1
            script:
              - yarn install
              - npx playwright install --with-deps
              - (yarn serve &) && yarn playwright test --shard 1/3
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 2
            script:
              - yarn install
              - npx playwright install --with-deps
              - (yarn serve &) && yarn playwright test --shard 2/3
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 3
            script:
              - yarn install
              - npx playwright install --with-deps
              - (yarn serve &) && yarn playwright test --shard 3/3
            artifacts:
              - test-results/**
              - playwright-report/**
