image:
  name: node:18
options:
  size: 4x

pipelines:
  default:
    - parallel:
        - step:
            name: Shard 1
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 1/25
            artifacts:
              - test-results/**
              - playwright-report/**

        - step:
            name: Shard 2
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 2/25
            artifacts:
              - test-results/**
              - playwright-report/**

        - step:
            name: Shard 3
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 3/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 4
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 4/25
            artifacts:
              - test-results/**
              - playwright-report/**

        - step:
            name: Shard 5
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 5/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 6
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 6/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 7
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 7/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 8
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 8/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 9
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 9/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 10
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 10/25
            artifacts:
              - test-results/**
              - playwright-report/**

            name: Shard 11
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 11/25
            artifacts:
              - test-results/**
              - playwright-report/**

        - step:
            name: Shard 12
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 12/25
            artifacts:
              - test-results/**
              - playwright-report/**

        - step:
            name: Shard 13
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 13/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 14
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 14/25
            artifacts:
              - test-results/**
              - playwright-report/**

        - step:
            name: Shard 15
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 15/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 16
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 16/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 17
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 17/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 18
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 18/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 19
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 19/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 20
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 20/25
            artifacts:
              - test-results/**
              - playwright-report/**

        - step:
            name: Shard 21
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 21/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 22
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 22/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 23
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 23/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 24
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 24/25
            artifacts:
              - test-results/**
              - playwright-report/**
        - step:
            name: Shard 25
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test --shard 25/25
            artifacts:
              - test-results/**
              - playwright-report/**
