image:
  name: node:18
options:
  size: 2x

pipelines:
  default:
    - parallel:
        - step:
            name: Install dependencies
            script:
              - yarn install
              - npx playwright install --with-deps
              - yarn playwright test
